import { ProjectCategory, type ProjectEntry } from '@/app/types/v2';

export const ALL_PROJECTS_FILTER: string = 'all';

export const PROJECT_INDEX_INTRO: string =
    'The full list, from products I founded to client builds and weekend experiments. Filter by the kind of problem.';

export const PROJECT_FILTERS: { value: string; label: string }[] = [
    { value: ALL_PROJECTS_FILTER, label: 'All' },
    { value: ProjectCategory.Fintech, label: 'Fintech' },
    { value: ProjectCategory.Events, label: 'Events' },
    { value: ProjectCategory.Commerce, label: 'Commerce' },
    { value: ProjectCategory.HrAndHiring, label: 'HR and hiring' },
    { value: ProjectCategory.Ai, label: 'AI' },
    { value: ProjectCategory.Place, label: 'Travel, hospitality and health' },
    { value: ProjectCategory.Tools, label: 'Tools and experiments' },
];

const CASE_STUDY_NOTE: string = 'Case study above';
const CARD_NOTE: string = 'Card above';

export const PROJECTS: ProjectEntry[] = [
    {
        id: 'p-ticketsdeck',
        name: 'Ticketsdeck Events',
        summary: 'Event ticketing and check-in',
        detail: CASE_STUDY_NOTE,
        part: 'Founder, CTO',
        years: '2023 - now',
        categories: [ProjectCategory.Events],
        href: '#ticketsdeck',
    },
    {
        id: 'p-cashdrive',
        name: 'CashDrive',
        summary: 'Car-backed lending',
        detail: CASE_STUDY_NOTE,
        part: 'Lead frontend',
        years: '2025 - now',
        categories: [ProjectCategory.Fintech],
        href: '#cashdrive',
    },
    {
        id: 'p-plugiq',
        name: 'PlugIQ',
        summary: 'No-code workflow platform',
        detail: CASE_STUDY_NOTE,
        part: 'Software engineer',
        years: '2025 - 2026',
        categories: [ProjectCategory.Tools, ProjectCategory.Ai],
        href: '#plugiq',
    },
    {
        id: 'p-mirratal',
        name: 'Mirratal',
        summary: 'AI voice interviews for hiring',
        detail: CASE_STUDY_NOTE,
        part: 'Sole engineer',
        years: '2026',
        categories: [ProjectCategory.HrAndHiring, ProjectCategory.Ai],
        href: '#mirratal',
    },
    {
        id: 'p-chequein',
        name: 'ChequeIn',
        summary: 'Payroll and earned wage access',
        detail: CASE_STUDY_NOTE,
        part: 'Frontend lead',
        years: '2026',
        categories: [ProjectCategory.Fintech, ProjectCategory.HrAndHiring, ProjectCategory.Ai],
        href: '#chequein',
    },
    {
        id: 'p-owaambe',
        name: 'Owaambe',
        summary: 'Invitations, RSVPs and gifts',
        detail: CASE_STUDY_NOTE,
        part: 'Sole engineer',
        years: '2026',
        categories: [ProjectCategory.Events],
        href: '#owaambe',
    },
    {
        id: 'p-godofreda',
        name: 'Godofreda',
        summary: 'Factory-direct video shopping',
        detail: CARD_NOTE,
        part: 'Technical lead',
        years: '2026',
        categories: [ProjectCategory.Commerce],
        href: '#godofreda',
    },
    {
        id: 'p-stylist-piazza',
        name: 'Stylist Piazza',
        summary: 'Beauty booking app',
        detail: CARD_NOTE,
        part: 'Lead mobile',
        years: '2024',
        categories: [ProjectCategory.Commerce],
        href: '#stylist-piazza',
    },
    {
        id: 'p-mozara',
        name: 'Mozara Autos',
        summary: 'Car import marketplace',
        detail: CARD_NOTE,
        part: 'Lead engineer',
        years: '2026',
        categories: [ProjectCategory.Commerce],
        href: '#mozara',
    },
    {
        id: 'p-oneflare',
        name: 'Oneflare HMS',
        summary: 'Hotel management backend',
        detail: 'One multi-tenant backend behind a hotel system, a maintenance app and two admin consoles.',
        part: 'Lead backend',
        years: '2026',
        categories: [ProjectCategory.Place],
    },
    {
        id: 'p-sabibid',
        name: 'SabiBid',
        summary: 'Online auctions with live bidding',
        detail: 'Bid drawer, seller auction tools, wallet and watchlist.',
        part: 'Frontend engineer',
        years: '2025 - 2026',
        categories: [ProjectCategory.Commerce],
    },
    {
        id: 'p-bisi',
        name: 'BiSi Connect',
        summary: 'Campus marketplace for students',
        detail: 'Wrote nearly all of the NestJS API, plus auth and listings on the web.',
        part: 'Backend lead',
        years: '2025 - 2026',
        categories: [ProjectCategory.Commerce],
    },
    {
        id: 'p-belmark',
        name: 'Belmark FarmFresh',
        summary: 'Farm-to-market grocery store',
        detail: 'Built the storefront alone: catalogue, cart, checkout and order history.',
        part: 'Storefront engineer',
        years: '2025',
        categories: [ProjectCategory.Commerce],
    },
    {
        id: 'p-baoja',
        name: 'Baoja',
        summary: 'Lagos market delivery',
        detail: 'A two-week build: three-sided app, escrow ledger on Paystack, live rider tracking.',
        part: 'Sole engineer',
        years: '2026',
        categories: [ProjectCategory.Commerce, ProjectCategory.Fintech],
    },
    {
        id: 'p-orineum',
        name: 'Orineum',
        summary: 'AI help for US visa petitions',
        detail: 'Application wizard, live petition updates, document uploads. Landing page solo.',
        part: 'Frontend engineer',
        years: '2025 - 2026',
        categories: [ProjectCategory.Ai],
    },
    {
        id: 'p-dimlang',
        name: 'Dimlang',
        summary: 'AI video repurposing for creators',
        detail: 'Design system, auth, and the transcribe, remix and scheduler screens.',
        part: 'Frontend engineer',
        years: '2025 - 2026',
        categories: [ProjectCategory.Ai],
    },
    {
        id: 'p-minnt',
        name: 'Minnt',
        summary: 'Admin console for a fintech super-app',
        detail: 'Wallets, KYC review, payouts and fee configuration screens.',
        part: 'Sole engineer',
        years: '2026',
        categories: [ProjectCategory.Fintech],
    },
    {
        id: 'p-shiftsync',
        name: 'ShiftSync',
        summary: 'Staff scheduling across locations',
        detail: 'Rule checks for conflicts and overtime, shift swaps, real-time updates.',
        part: 'Sole engineer',
        years: '2026',
        categories: [ProjectCategory.HrAndHiring],
    },
    {
        id: 'p-lagos',
        name: 'Lagos Health District VI',
        summary: 'Public health district website',
        detail: 'Built for older readers: large type, high contrast, WCAG AA.',
        part: 'Sole engineer',
        years: '2026',
        categories: [ProjectCategory.Place],
    },
    {
        id: 'p-hyperframes',
        name: 'HyperFrames',
        summary: 'AI-directed motion graphics',
        detail: 'Rules and a build pipeline for an AI agent to direct HTML and GSAP videos.',
        part: 'Creator',
        years: '2026',
        categories: [ProjectCategory.Tools, ProjectCategory.Ai],
    },
    {
        id: 'p-trading',
        name: 'Trading bots',
        summary: 'Rule-based MetaTrader 5 bots',
        detail: 'Position sizing, spread guards and a daily loss kill switch, in Python.',
        part: 'Creator',
        years: '2026',
        categories: [ProjectCategory.Tools, ProjectCategory.Fintech],
    },
    {
        id: 'p-247',
        name: '247 Travels',
        summary: 'Flight booking',
        detail: 'Built the frontend of the booking web app.',
        part: 'Frontend, at Xown',
        years: '2022 - 2025',
        categories: [ProjectCategory.Place],
        href: 'https://247travels.com',
        isExternal: true,
    },
    {
        id: 'p-mcnif',
        name: 'McNif Cuisine',
        summary: 'Restaurant site for a UK restaurant',
        detail: 'Menu browsing and reservations.',
        part: 'Engineer, at Xown',
        years: '2022 - 2025',
        categories: [ProjectCategory.Place],
    },
    {
        id: 'p-bablo',
        name: 'Bablo Homes',
        summary: 'Real estate platform, UK',
        detail: 'Property listings and enquiries.',
        part: 'Engineer, at Xown',
        years: '2022 - 2025',
        categories: [ProjectCategory.Commerce],
        href: 'https://bablohomes.co.uk',
        isExternal: true,
    },
];
